Resources:
  EmployeeTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-employee-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: firstName
          AttributeType: S
        - AttributeName: lastName
          AttributeType: S
        - AttributeName: dateOfJoining
          AttributeType: 'N'
        - AttributeName: dateOfBirth
          AttributeType: 'N'
        - AttributeName: salary
          AttributeType: 'N'
        - AttributeName: department
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: position
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: firstNameGlobalIndex
          KeySchema:
            - AttributeName: firstName
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: lastNameGlobalIndex
          KeySchema:
            - AttributeName: lastName
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: dateOfJoiningGlobalIndex
          KeySchema:
            - AttributeName: dateOfJoining
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: dateOfBirthGlobalIndex
          KeySchema:
            - AttributeName: dateOfBirth
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: salaryGlobalIndex
          KeySchema:
            - AttributeName: salary
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: departmentGlobalIndex
          KeySchema:
            - AttributeName: department
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: statusGlobalIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: positionGlobalIndex
          KeySchema:
            - AttributeName: position
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
